[package]
name = "raytracing-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
exr = "1.4.0"
glam = "0.20.5"